##Importing Libraries and neccessary pickle files

In [ ]:
import time
import random
import pandas as pd
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

Pkl_Filename = "Median_values.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    median= pickle.load(file)

Pkl_Filename = "minmax.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    scalar= pickle.load(file)

Pkl_Filename = "random_imputer.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    random_imp= pickle.load(file)

Pkl_Filename = "standard_dev.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    standard= pickle.load(file)

Pkl_Filename = "XGBoost_cv_.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    XGBoost= pickle.load(file)

##Reading the data

In [5]:
Data=pd.read_csv('equip_failures_training_set.csv')
Data.head()

   id  target  ...  sensor106_measure sensor107_measure
0   1       0  ...                  0                 0
1   2       0  ...                  0                 0
2   3       0  ...                  0                 0
3   4       0  ...                  4                32
4   5       0  ...                  0                 0

[5 rows x 172 columns]

In [120]:
y=Data[['target']]
X=Data.drop(['target'],axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,stratify=y) #splitting the dataset into train and test data

In [131]:
rand=random.randrange(0,len(X_test)) 
X=X_test.iloc[rand,:]     #Selecting a random value from the test data

#its target to check
y=y_test.iloc[rand]
print('Actual target : ',y)

Actual target :  target    0
Name: 34205, dtype: int64

#Function-1

In [125]:
def final_fun_1(X):
  X=pd.DataFrame(X).transpose()
  X=X.replace('na',np.NaN)
  X=X.astype(float)
  X.drop('id',axis=1,inplace=True)
  less_var=['sensor7_histogram_bin0','sensor7_histogram_bin1','sensor19_measure','sensor21_measure','sensor24_histogram_bin0','sensor24_histogram_bin1','sensor24_histogram_bin2','sensor24_histogram_bin3',
            'sensor24_histogram_bin4','sensor24_histogram_bin9','sensor25_histogram_bin9','sensor64_histogram_bin0','sensor100_measure','sensor106_measure','sensor2_measure','sensor18_measure',
            'sensor54_measure','sensor58_measure','sensor107_measure','sensor68_measure', 'sensor40_measure', 'sensor42_measure', 'sensor43_measure', 'sensor41_measure']
  X.drop(less_var,inplace=True,axis=1)
  features=['sensor4_measure','sensor36_measure','sensor37_measure','sensor38_measure','sensor39_measure','sensor56_measure',
          'sensor57_measure','sensor65_measure',
          'sensor70_measure','sensor71_measure','sensor72_measure','sensor73_measure','sensor74_measure',
          'sensor75_measure','sensor76_measure','sensor77_measure','sensor78_measure']
  for i in X.columns:
    if i not in features:
      X[i].fillna(median[i],inplace=True)
    if i=='sensor4_measure' or i=='sensor56_measure' or i=='sensor65_measure':
      X[i].fillna(standard[i],inplace=True)
  Random_impute=X[features].copy()
  Random_impute.drop('sensor4_measure',axis=1,inplace=True)
  Random_impute.drop('sensor56_measure',axis=1,inplace=True)
  Random_impute.drop('sensor65_measure',axis=1,inplace=True)
  imp=random_imp.transform(Random_impute)
  X['sensor36_measure']=imp['sensor36_measure']
  X['sensor37_measure']=imp['sensor37_measure']
  X['sensor38_measure']=imp['sensor38_measure']
  X['sensor39_measure']=imp['sensor39_measure']
  X['sensor57_measure']=imp['sensor57_measure']
  X['sensor70_measure']=imp['sensor70_measure']
  X['sensor71_measure']=imp['sensor71_measure']
  X['sensor72_measure']=imp['sensor72_measure']
  X['sensor73_measure']=imp['sensor73_measure']
  X['sensor74_measure']=imp['sensor74_measure']
  X['sensor75_measure']=imp['sensor75_measure']
  X['sensor76_measure']=imp['sensor76_measure']
  X['sensor77_measure']=imp['sensor77_measure']
  X['sensor78_measure']=imp['sensor78_measure']
  corr=['sensor95_measure','sensor61_measure', 'sensor33_measure', 'sensor7_histogram_bin7', 'sensor25_histogram_bin5','sensor26_histogram_bin3','sensor26_histogram_bin0', 'sensor91_measure',
  'sensor69_histogram_bin3','sensor67_measure','sensor26_histogram_bin6','sensor8_measure','sensor64_histogram_bin3','sensor14_measure','sensor34_measure','sensor47_measure','sensor104_measure',
 'sensor26_histogram_bin5','sensor15_measure','sensor105_histogram_bin3','sensor88_measure','sensor105_histogram_bin2','sensor64_histogram_bin5','sensor32_measure','sensor64_histogram_bin4',
 'sensor16_measure','sensor26_histogram_bin2','sensor26_histogram_bin4','sensor69_histogram_bin4','sensor26_histogram_bin1','sensor45_measure','sensor64_histogram_bin6','sensor105_histogram_bin4',
 'sensor69_histogram_bin2','sensor69_histogram_bin0','sensor17_measure','sensor27_measure','sensor46_measure','sensor64_histogram_bin8','sensor69_histogram_bin5','sensor89_measure',
 'sensor64_histogram_bin2','sensor73_measure']
  X.drop(corr,axis=1,inplace=True)
  X['sensor48_log']=np.log(X['sensor48_measure']+1)
  X['sensor59_log']=np.log(X['sensor59_measure']+1)
  X['sensor53_log']=np.log(X['sensor53_measure']+1)
  X['sensor105_log']=np.log(X['sensor105_histogram_bin0']+1)
  X['sensor69_histogram_bin6_log']=np.log(X['sensor69_histogram_bin6']+1)
  X['histogram_sum_7']=(X['sensor7_histogram_bin2']+X['sensor7_histogram_bin3']+X['sensor7_histogram_bin4']+X['sensor7_histogram_bin5']+X['sensor7_histogram_bin6']+X['sensor7_histogram_bin8']+X['sensor7_histogram_bin9'])**(1/4)
  X['histogram_sum_24']=(X['sensor24_histogram_bin5']+X['sensor24_histogram_bin6']+X['sensor24_histogram_bin7']+X['sensor24_histogram_bin8'])**(1/4)
  X['histogram_sum_26']=(X['sensor26_histogram_bin7']+X['sensor26_histogram_bin8']+X['sensor26_histogram_bin9'])**(1/4)
  X['histogram_sum_64']=(X['sensor64_histogram_bin7']+X['sensor64_histogram_bin1']+X['sensor64_histogram_bin9'])**(1/4)
  X['histogram_sum_69']=(X['sensor69_histogram_bin1']+X['sensor69_histogram_bin6']+X['sensor69_histogram_bin7']+X['sensor69_histogram_bin8']+X['sensor69_histogram_bin9'])**(1/4)
  X['histogram_sum_25']=(X['sensor25_histogram_bin0']+X['sensor25_histogram_bin1']+X['sensor25_histogram_bin2']+X['sensor25_histogram_bin3']+X['sensor25_histogram_bin4']+X['sensor25_histogram_bin6']+X['sensor25_histogram_bin7']+X['sensor25_histogram_bin8'])**(1/4)
  X['histogram_sum_105']=(X['sensor105_histogram_bin0']+X['sensor105_histogram_bin1']+X['sensor105_histogram_bin5']+X['sensor105_histogram_bin6']+X['sensor105_histogram_bin8']+X['sensor105_histogram_bin9'])**(1/4)
  names=X.columns
  X=scalar.transform(X)
  X=pd.DataFrame(X)
  X.columns=names
  return ("Predicted target :",XGBoost.predict(X)[0])

# Function-2

In [117]:
def final_fun_2(X,Y):
  X=X.replace('na',np.NaN)
  X=X.astype(float)
  X.drop('id',axis=1,inplace=True)
  less_var=['sensor7_histogram_bin0','sensor7_histogram_bin1','sensor19_measure','sensor21_measure','sensor24_histogram_bin0','sensor24_histogram_bin1','sensor24_histogram_bin2','sensor24_histogram_bin3',
            'sensor24_histogram_bin4','sensor24_histogram_bin9','sensor25_histogram_bin9','sensor64_histogram_bin0','sensor100_measure','sensor106_measure','sensor2_measure','sensor18_measure',
            'sensor54_measure','sensor58_measure','sensor107_measure','sensor68_measure', 'sensor40_measure', 'sensor42_measure', 'sensor43_measure', 'sensor41_measure']
  X.drop(less_var,inplace=True,axis=1)
  features=['sensor4_measure','sensor36_measure','sensor37_measure','sensor38_measure','sensor39_measure','sensor56_measure',
          'sensor57_measure','sensor65_measure',
          'sensor70_measure','sensor71_measure','sensor72_measure','sensor73_measure','sensor74_measure',
          'sensor75_measure','sensor76_measure','sensor77_measure','sensor78_measure']
  for i in X.columns:
    if i not in features:
      X[i].fillna(median[i],inplace=True)
    if i=='sensor4_measure' or i=='sensor56_measure' or i=='sensor65_measure':
      X[i].fillna(standard[i],inplace=True)
  Random_impute=X[features].copy()
  Random_impute.drop('sensor4_measure',axis=1,inplace=True)
  Random_impute.drop('sensor56_measure',axis=1,inplace=True)
  Random_impute.drop('sensor65_measure',axis=1,inplace=True)
  imp=random_imp.transform(Random_impute)
  X['sensor36_measure']=imp['sensor36_measure']
  X['sensor37_measure']=imp['sensor37_measure']
  X['sensor38_measure']=imp['sensor38_measure']
  X['sensor39_measure']=imp['sensor39_measure']
  X['sensor57_measure']=imp['sensor57_measure']
  X['sensor70_measure']=imp['sensor70_measure']
  X['sensor71_measure']=imp['sensor71_measure']
  X['sensor72_measure']=imp['sensor72_measure']
  X['sensor73_measure']=imp['sensor73_measure']
  X['sensor74_measure']=imp['sensor74_measure']
  X['sensor75_measure']=imp['sensor75_measure']
  X['sensor76_measure']=imp['sensor76_measure']
  X['sensor77_measure']=imp['sensor77_measure']
  X['sensor78_measure']=imp['sensor78_measure']
  corr=['sensor95_measure','sensor61_measure', 'sensor33_measure', 'sensor7_histogram_bin7', 'sensor25_histogram_bin5','sensor26_histogram_bin3','sensor26_histogram_bin0', 'sensor91_measure',
  'sensor69_histogram_bin3','sensor67_measure','sensor26_histogram_bin6','sensor8_measure','sensor64_histogram_bin3','sensor14_measure','sensor34_measure','sensor47_measure','sensor104_measure',
 'sensor26_histogram_bin5','sensor15_measure','sensor105_histogram_bin3','sensor88_measure','sensor105_histogram_bin2','sensor64_histogram_bin5','sensor32_measure','sensor64_histogram_bin4',
 'sensor16_measure','sensor26_histogram_bin2','sensor26_histogram_bin4','sensor69_histogram_bin4','sensor26_histogram_bin1','sensor45_measure','sensor64_histogram_bin6','sensor105_histogram_bin4',
 'sensor69_histogram_bin2','sensor69_histogram_bin0','sensor17_measure','sensor27_measure','sensor46_measure','sensor64_histogram_bin8','sensor69_histogram_bin5','sensor89_measure',
 'sensor64_histogram_bin2','sensor73_measure']
  X.drop(corr,axis=1,inplace=True)
  X['sensor48_log']=np.log(X['sensor48_measure']+1)
  X['sensor59_log']=np.log(X['sensor59_measure']+1)
  X['sensor53_log']=np.log(X['sensor53_measure']+1)
  X['sensor105_log']=np.log(X['sensor105_histogram_bin0']+1)
  X['sensor69_histogram_bin6_log']=np.log(X['sensor69_histogram_bin6']+1)
  X['histogram_sum_7']=(X['sensor7_histogram_bin2']+X['sensor7_histogram_bin3']+X['sensor7_histogram_bin4']+X['sensor7_histogram_bin5']+X['sensor7_histogram_bin6']+X['sensor7_histogram_bin8']+X['sensor7_histogram_bin9'])**(1/4)
  X['histogram_sum_24']=(X['sensor24_histogram_bin5']+X['sensor24_histogram_bin6']+X['sensor24_histogram_bin7']+X['sensor24_histogram_bin8'])**(1/4)
  X['histogram_sum_26']=(X['sensor26_histogram_bin7']+X['sensor26_histogram_bin8']+X['sensor26_histogram_bin9'])**(1/4)
  X['histogram_sum_64']=(X['sensor64_histogram_bin7']+X['sensor64_histogram_bin1']+X['sensor64_histogram_bin9'])**(1/4)
  X['histogram_sum_69']=(X['sensor69_histogram_bin1']+X['sensor69_histogram_bin6']+X['sensor69_histogram_bin7']+X['sensor69_histogram_bin8']+X['sensor69_histogram_bin9'])**(1/4)
  X['histogram_sum_25']=(X['sensor25_histogram_bin0']+X['sensor25_histogram_bin1']+X['sensor25_histogram_bin2']+X['sensor25_histogram_bin3']+X['sensor25_histogram_bin4']+X['sensor25_histogram_bin6']+X['sensor25_histogram_bin7']+X['sensor25_histogram_bin8'])**(1/4)
  X['histogram_sum_105']=(X['sensor105_histogram_bin0']+X['sensor105_histogram_bin1']+X['sensor105_histogram_bin5']+X['sensor105_histogram_bin6']+X['sensor105_histogram_bin8']+X['sensor105_histogram_bin9'])**(1/4)
  names=X.columns
  X=scalar.transform(X)
  X=pd.DataFrame(X)
  X.columns=names
  final_pred=XGBoost.predict(X)
  return ('F1 Score : ', f1_score(Y,final_pred, average='binary'))

## Prediction and the performance metric(F1 Score)

In [ ]:
start_time = time.time()
print(final_fun_1(X))
print("--- %s seconds ---" % (time.time() - start_time))

('Predicted target :', 0.0)
--- 0.1210942268371582 seconds ---

In [129]:
start_time = time.time()
print(final_fun_2(X_test,y_test))
print("--- %s seconds ---" % (time.time() - start_time))

('F1 Score : ', 0.8247422680412372)
--- 1.633291244506836 seconds ---